# Generated by Django 4.0.6 on 2023-10-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
